# Generated by Django 5.0.2 on 2024-02-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_basketproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='продукт'),
        ),
    ]
